name: CI/CD - Development Branch

on:
  push:
    paths:
      - ".github/workflows/dev.yml"
      - "core/**/*"
      - "adp/**/*"
      - "dp/**/*"
      - "oc/**/*"
      - "sim/**/*"

jobs:
  build:
    uses: Abdullahi127/Reusable_Workflows/.github/workflows/build.yml@main

  deployment:
    needs: build
    uses: Abdullahi127/Reusable_Workflows/.github/workflows/deployDevEnvs.yml@main
# asfasdf
