name: CI/CD - Development Branch

on:
  push:
    paths:
      - ".github/workflows/dev.yml"
      - "core/**/*"
      - "adp/**/*"
      - "dp/**/*"
      - "oc/**/*"
      - "sim/**/*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout dev repo
        uses: actions/checkout@v3
        with:
          ref: dev
          fetch-depth: 0

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "gradle"

      - name: build core
        run: |
          chmod +x ./gradlew
          ./gradlew core:setProjectVersion --projectVersion=1.0.0 --alias=core core:build

      - name: upload adp
        uses: actions/upload-artifact@v3
        with:
          name: deploy
          path: ./core/build/libs
          retention-days: 1

  deployment:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        id: download
        with:
          name: deploy
          path: path/to/artifacts

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: path/to/artifacts

      - name: "Echo download path"
        run: |
          echo "${{ steps.download.outputs.download-path }}"
          for FILE in ${{ steps.download.outputs.download-path }}/*.jar; do
              echo "$FILE";
              curl "http://localhost:8080/componentManagement/api/components" -F file1=@$FILE
          done;

# jobs:
#   build:
#     uses: Abdullahi127/Reusable_Workflows/.github/workflows/build.yml@main
#   deployment:
#     needs: build
#     uses: Abdullahi127/Reusable_Workflows/.github/workflows/deployDevEnvs.yml@main
