name: CI/CD - Development Branch

on:
  push:
    paths:
      - ".github/workflows/dev.yml"
      - "src/**"
      - "build.gradle"
      - "settings.gradle"

jobs:
  build:
    uses: Abdullahi127/Reusable_Workflows/.github/workflows/gameserver-build.yml@main

  deployment:
    needs: buildPublish
    uses: Abdullahi127/Reusable_Workflows/.github/workflows/deployDevEnvs.yml@main
